spring:
  application:
    name: metrics_service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/metricsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: vGjKGHwBL/gIYjMfuTWrEx6KDuOWoPLpnVwAKyRfNB0mZXxeJwSeyunhGAUm64tS8UpF3wH7bADviTGAtPti/g==
  expiration: 86400000

server:
  port: 8088

elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  scheme: ${ELASTICSEARCH_SCHEME:http}