spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG
    com.dxc.observability.user_service.security: DEBUG
server:
  port: 8089